# Generated by Django 2.0.2 on 2018-02-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.TextField(null=True)),
                ('ivr', models.TextField(null=True)),
            ],
        ),
    ]
